name: Workflow CI

on:
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  linter:
    name: Проверка качества кода
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10","3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Установка Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{matrix.python-version}}
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8 wemake-python-styleguide flake8-html flake8-github flake8-bandit bandit
      - name: Прогон через wemake-python-styleguide с разными версиями
        if: always()
        id: flake8
        run: flake8 .
      - name: Проверка типизации
        id: mypy
        uses: jpetrucciani/mypy-check@0.991
        with:
          python_version: 3.12
      - name: Отправка сообщения об успешности пайплайна
        if: always()
        uses: robotomize/notify-telegram@v0.2.4
        with:
          chat: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          status: ${{ steps.flake8.outcome == 'success' && steps.mypy.outcome == 'success' }}
          message: |
            ${{ github.actor }} created pull-request:
            PR SHA: ${{ github.event.pull_request.head.sha }}
            Repository: ${{ github.repository }}
            Status: ${{ steps.flake8.outcome == 'success' && steps.mypy.outcome == 'success' }} на версии ${{matrix.python-version}}
  
  report:
    name: Формирование отчета
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Установка Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
      - name: Unit test bookmark service
        id: pytest
        run: |
          cd bookmarks_service
          python -m venv .venv
          .venv/bin/activate
          pip install -r requirements.txt
          pytest
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8 wemake-python-styleguide flake8-html flake8-github flake8-bandit bandit
      - name: Прогон для формирования отчета
        run: flake8 . --format=html --htmldir=flake-report
      - name: Сохранение артефактов HTML
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: html-reports
          path: flake-report/*.html
      - name: Формирование артефактов для GH
        id: storeghartefacts
        if: always()
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: linting-summary
          path: flake-report
          retention-days: 10
  

        
        
    
      

      
        
          
           
      
